/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityIndexRouteImport } from './routes/city.index'
import { Route as CityOpportunityRouteImport } from './routes/city.opportunity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIndexRoute = CityIndexRouteImport.update({
  id: '/city/',
  path: '/city/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityOpportunityRoute = CityOpportunityRouteImport.update({
  id: '/city/opportunity',
  path: '/city/opportunity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city/opportunity': typeof CityOpportunityRoute
  '/city/': typeof CityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city/opportunity': typeof CityOpportunityRoute
  '/city': typeof CityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city/opportunity': typeof CityOpportunityRoute
  '/city/': typeof CityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/city/opportunity' | '/city/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/city/opportunity' | '/city'
  id: '__root__' | '/' | '/city/opportunity' | '/city/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityOpportunityRoute: typeof CityOpportunityRoute
  CityIndexRoute: typeof CityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/': {
      id: '/city/'
      path: '/city'
      fullPath: '/city/'
      preLoaderRoute: typeof CityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/opportunity': {
      id: '/city/opportunity'
      path: '/city/opportunity'
      fullPath: '/city/opportunity'
      preLoaderRoute: typeof CityOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityOpportunityRoute: CityOpportunityRoute,
  CityIndexRoute: CityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
