/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityIndexRouteImport } from './routes/city.index'
import { Route as CityOpportunityRouteImport } from './routes/city.opportunity'
import { Route as PublicIndexRouteImport } from './routes/public.index'
import { Route as PublicProjectIdRouteImport } from './routes/public.project.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIndexRoute = CityIndexRouteImport.update({
  id: '/city/',
  path: '/city/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityOpportunityRoute = CityOpportunityRouteImport.update({
  id: '/city/opportunity',
  path: '/city/opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/public/',
  path: '/public/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProjectIdRoute = PublicProjectIdRouteImport.update({
  id: '/public/project/$id',
  path: '/public/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city/opportunity': typeof CityOpportunityRoute
  '/city/': typeof CityIndexRoute
  '/public/': typeof PublicIndexRoute
  '/public/project/$id': typeof PublicProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city/opportunity': typeof CityOpportunityRoute
  '/city': typeof CityIndexRoute
  '/public': typeof PublicIndexRoute
  '/public/project/$id': typeof PublicProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city/opportunity': typeof CityOpportunityRoute
  '/city/': typeof CityIndexRoute
  '/public/': typeof PublicIndexRoute
  '/public/project/$id': typeof PublicProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/city/opportunity' | '/city/' | '/public/' | '/public/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/city/opportunity' | '/city' | '/public' | '/public/project/$id'
  id:
    | '__root__'
    | '/'
    | '/city/opportunity'
    | '/city/'
    | '/public/'
    | '/public/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityOpportunityRoute: typeof CityOpportunityRoute
  CityIndexRoute: typeof CityIndexRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProjectIdRoute: typeof PublicProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/': {
      id: '/city/'
      path: '/city'
      fullPath: '/city/'
      preLoaderRoute: typeof CityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/opportunity': {
      id: '/city/opportunity'
      path: '/city/opportunity'
      fullPath: '/city/opportunity'
      preLoaderRoute: typeof CityOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/': {
      id: '/public/'
      path: '/public'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/project/$id': {
      id: '/public/project/$id'
      path: '/public/project/$id'
      fullPath: '/public/project/$id'
      preLoaderRoute: typeof PublicProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityOpportunityRoute: CityOpportunityRoute,
  CityIndexRoute: CityIndexRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProjectIdRoute: PublicProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
